-- Demo catalog: finished 3D-printed goods.
-- Images live in public/images/ and are served by Nuxt from the site root.

insert into public.products (slug, name, description, price_cents, image_url) values
  ('articulated-dragon',    'Articulated Dragon',    'Print-in-place PLA, 92 links, 11" nose to tail. Every joint comes off the printer already moving, so there is nothing to glue or assemble. The body coils, arches and holds a pose on a shelf or a desk. Wipe it with a dry cloth and keep it out of a hot car, since PLA softens in direct summer sun.', 2400, '/images/articulated-dragon.jpg'),
  ('desk-cable-organizer',  'Desk Cable Organizer',  'Weighted PETG base, five channels, non-slip pads. Each channel grips a cable from a phone lead up to a laptop barrel plug, and the weight means a cable stays put when you pull the end free. The pads lift it clear of the desk so it does not mark a finish. PETG handles a sunlit desk better than PLA.', 1600, '/images/desk-cable-organizer.jpg'),
  ('self-watering-planter', 'Self-Watering Planter', 'Two-part PETG shell, wicking reservoir, 5" pot. The inner pot sits above a reservoir and draws water up through a wick, so a herb or a small houseplant goes a week or two between fills. A side window shows the level without lifting anything out. PETG is food-safe and does not go brittle in a bright window.', 3200, '/images/self-watering-planter.jpg'),
  ('lithophane-night-lamp', 'Lithophane Night Lamp', 'Translucent PLA panel, warm LED, USB-C powered. The image is printed as varying thickness rather than colour, so it reads as a faint pattern by day and resolves into a picture once the lamp is on. The LED runs warm and dim enough for a bedside table. Any USB-C charger or laptop port powers it, and the panel lifts out if you want to swap the picture.', 4800, '/images/lithophane-night-lamp.jpg'),
  ('hex-dice-tower',        'Hex Dice Tower',        'Matte PLA, felt-lined tray, folds flat for travel. Dice tumble through three internal baffles and land in the tray rather than across the table, which settles most arguments about a cocked die. The felt keeps the noise down in a quiet room. It collapses into a flat stack that fits a board game box alongside the board.', 5400, '/images/hex-dice-tower.jpg'),
  ('stackable-drawer-bins', 'Stackable Drawer Bins', 'Six nesting PETG bins, ribbed walls, 2" deep. They stack when full and nest inside each other when empty, so an unused set takes up one bin of space. The ribs stop two full bins sliding apart when a drawer is opened hard. Sized for a standard desk drawer, and they wash in warm soapy water.', 2900, '/images/stackable-drawer-bins.jpg')
on conflict (slug) do nothing;

-- Downloadable files. Sizes are bytes; the storefront formats them.
insert into public.products (slug, name, description, price_cents, kind, file_name, file_format, file_size_bytes) values
  ('articulated-dragon-project', 'Articulated Dragon Project File', 'Slicer project with print settings, supports and two filament colours set up. Opens in PrusaSlicer, Orca or Bambu Studio. Everything that makes the joints come out moving is already dialled in, including the clearances that decide whether the links seize. Load it, pick your printer profile and send it.', 900,  'digital', 'articulated-dragon.3mf', '3MF', 26004684),
  ('hex-dice-tower-model',       'Hex Dice Tower Model',            'Plain triangle mesh, the format every desktop printer accepts. Slice it yourself and choose your own layer height and infill. The tower is split into parts that each sit flat on the bed, so none of them needs support. Scale it up for larger dice if your printer has the height.',        600,  'digital', 'hex-dice-tower.stl',    'STL', 8598323),
  ('drawer-bins-parametric',     'Drawer Bins Parametric Source',   'Editable CAD source for the drawer bins. Change the width, depth and rib spacing, then export your own sizes. STEP opens in Fusion, Onshape, FreeCAD and SolidWorks, and keeps the real geometry rather than a mesh approximation, so an edited edge stays a clean curve. Measure your drawer first: the supplied sizes suit a standard one.',                     1400, 'digital', 'drawer-bins.step',      'STEP', 3355443)
on conflict (slug) do nothing;
