-- Demo catalog: finished 3D-printed goods.
-- Images live in public/images/ and are served by Nuxt from the site root.

insert into public.products (slug, name, description, price_cents, image_url) values
  ('articulated-dragon',    'Articulated Dragon',    'Print-in-place PLA, 92 links, 11" nose to tail. Every joint comes off the printer already moving, so there is nothing to glue or assemble. The body coils, arches and holds a pose on a shelf or a desk. Wipe it with a dry cloth and keep it out of a hot car, since PLA softens in direct summer sun.', 2400, '/images/articulated-dragon.jpg'),
  ('desk-cable-organizer',  'Desk Cable Organizer',  'Weighted PETG base, five channels, non-slip pads. Each channel grips a cable from a phone lead up to a laptop barrel plug, and the weight means a cable stays put when you pull the end free. The pads lift it clear of the desk so it does not mark a finish. PETG handles a sunlit desk better than PLA.', 1600, '/images/desk-cable-organizer.jpg'),
  ('self-watering-planter', 'Self-Watering Planter', 'Two-part PETG shell, wicking reservoir, 5" pot. The inner pot sits above a reservoir and draws water up through a wick, so a herb or a small houseplant goes a week or two between fills. A side window shows the level without lifting anything out. PETG is food-safe and does not go brittle in a bright window.', 3200, '/images/self-watering-planter.jpg'),
  ('lithophane-night-lamp', 'Lithophane Night Lamp', 'Translucent PLA panel, warm LED, USB-C powered. The image is printed as varying thickness rather than colour, so it reads as a faint pattern by day and resolves into a picture once the lamp is on. The LED runs warm and dim enough for a bedside table. Any USB-C charger or laptop port powers it, and the panel lifts out if you want to swap the picture.', 4800, '/images/lithophane-night-lamp.jpg'),
  ('hex-dice-tower',        'Hex Dice Tower',        'Matte PLA, felt-lined tray, folds flat for travel. Dice tumble through three internal baffles and land in the tray rather than across the table, which settles most arguments about a cocked die. The felt keeps the noise down in a quiet room. It collapses into a flat stack that fits a board game box alongside the board.', 5400, '/images/hex-dice-tower.jpg'),
  ('stackable-drawer-bins', 'Stackable Drawer Bins', 'Six nesting PETG bins, ribbed walls, 2" deep. They stack when full and nest inside each other when empty, so an unused set takes up one bin of space. The ribs stop two full bins sliding apart when a drawer is opened hard. Sized for a standard desk drawer, and they wash in warm soapy water.', 2900, '/images/stackable-drawer-bins.jpg')
on conflict (slug) do nothing;

-- Added 2026-09-11 so the catalogue is long enough to page through. These six
-- carry generated placeholder images rather than photographs; replace the file
-- in public/images/ and no code changes.
insert into public.products (slug, name, description, price_cents, image_url) values
  ('headphone-stand', 'Headphone Stand', 'Weighted PETG upright, 4" wide saddle, felt-topped. The saddle is wide enough that a padded band keeps its shape rather than denting overnight, and the weight in the base means one hand lifts the headphones off without the stand coming too. The felt stops it marking a gloss finish. It takes most over-ear sets, gaming headsets included.', 2600, '/images/headphone-stand.jpg'),
  ('phone-dock-charging', 'Angled Charging Dock', 'PLA body, 60-degree cradle, routed cable channel. The angle holds a phone at reading height on a desk rather than flat against it, so a message can be read without lifting it. The channel takes a USB-C lead from underneath and grips it, which keeps the cable from sliding out when the phone comes off. Fits a phone in a slim case.', 1800, '/images/phone-dock-charging.jpg'),
  ('pen-and-tool-cup', 'Pen and Tool Cup', 'Hexagonal PETG cup, 3.5" tall, divided into three. The dividers keep pens away from scalpels and tweezers, which is the difference between reaching in and looking first. The hex shape sits flat against two others if you want a row of them. Heavy enough not to tip when a full set of pens leans to one side.', 1400, '/images/pen-and-tool-cup.jpg'),
  ('monitor-riser-shelf', 'Monitor Riser Shelf', 'PETG legs, 15" span, rated to 8kg. It lifts a monitor to eye height and leaves a keyboard-sized gap underneath, which is most of what a desk tidy-up amounts to. The legs bolt to the shelf rather than printing as one piece, so it packs flat and survives a move. Tested with a 27-inch panel on its own stand.', 4400, '/images/monitor-riser-shelf.jpg'),
  ('cable-clip-set', 'Cable Clip Set', 'Twelve PETG clips, adhesive backed, three widths. The three sizes cover a phone lead, a laptop charger and a braided desk cable, so one set handles a whole desk rather than half of it. The adhesive is a 3M pad that lifts off a desk without leaving residue. Clips open from the side, so a cable comes out without unthreading the end.', 1200, '/images/cable-clip-set.jpg'),
  ('seed-starter-tray', 'Seed Starter Tray', 'PETG tray, nine cells, drip base included. Each cell holds enough compost for a seedling to reach its first true leaves, and the base catches what drains through so a windowsill stays dry. The cells push out from underneath, which lifts a root ball without tearing it. PETG takes a warm windowsill in summer without warping.', 2100, '/images/seed-starter-tray.jpg')
on conflict (slug) do nothing;

-- Downloadable files. Sizes are bytes; the storefront formats them.
insert into public.products (slug, name, description, price_cents, kind, file_name, file_format, file_size_bytes) values
  ('articulated-dragon-project', 'Articulated Dragon Project File', 'Slicer project with print settings, supports and two filament colours set up. Opens in PrusaSlicer, Orca or Bambu Studio. Everything that makes the joints come out moving is already dialled in, including the clearances that decide whether the links seize. Load it, pick your printer profile and send it.', 900,  'digital', 'articulated-dragon.3mf', '3MF', 26004684),
  ('hex-dice-tower-model',       'Hex Dice Tower Model',            'Plain triangle mesh, the format every desktop printer accepts. Slice it yourself and choose your own layer height and infill. The tower is split into parts that each sit flat on the bed, so none of them needs support. Scale it up for larger dice if your printer has the height.',        600,  'digital', 'hex-dice-tower.stl',    'STL', 8598323),
  ('drawer-bins-parametric',     'Drawer Bins Parametric Source',   'Editable CAD source for the drawer bins. Change the width, depth and rib spacing, then export your own sizes. STEP opens in Fusion, Onshape, FreeCAD and SolidWorks, and keeps the real geometry rather than a mesh approximation, so an edited edge stays a clean curve. Measure your drawer first: the supplied sizes suit a standard one.',                     1400, 'digital', 'drawer-bins.step',      'STEP', 3355443)
on conflict (slug) do nothing;
