// Regenerates server/types/database.ts from the live Supabase project.
//
// The Supabase CLI reads SUPABASE_ACCESS_TOKEN from the environment and npm
// does not load .env, so this reads the token out of .env first. The token is
// needed only here: nothing at build or run time reads it.
import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
// Which shop's database to read. Two deployments run this code against two
// projects, so a hardcoded ref would silently regenerate from the wrong one:
// the schemas are identical today, so the diff would be empty either way and
// the mistake would not show. Set SUPABASE_PROJECT_REF in .env to point it
// somewhere else; the default is the real shop.
const PROJECT_REF =
  process.env.SUPABASE_PROJECT_REF || fromEnvFile('SUPABASE_PROJECT_REF') || 'wfhhkdmgouyxnrxnbaeo'
const OUT = resolve(root, 'server/types/database.ts')

/** Reads one key out of .env without pulling in a dotenv dependency. */
function fromEnvFile(key) {
  let text
  try {
    text = readFileSync(resolve(root, '.env'), 'utf8')
  } catch {
    return undefined
  }
  for (const line of text.split(/\r?\n/)) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)$/.exec(line)
    if (match && match[1] === key) return match[2].trim().replace(/^["']|["']$/g, '')
  }
  return undefined
}

const token = process.env.SUPABASE_ACCESS_TOKEN || fromEnvFile('SUPABASE_ACCESS_TOKEN')
if (!token) {
  console.error('SUPABASE_ACCESS_TOKEN is not set. Put it in .env; see .env.example.')
  process.exit(1)
}

const result = spawnSync(
  'npx',
  ['--no-install', 'supabase', 'gen', 'types', 'typescript', '--project-id', PROJECT_REF, '--schema', 'public'],
  { env: { ...process.env, SUPABASE_ACCESS_TOKEN: token }, encoding: 'utf8', shell: process.platform === 'win32' }
)

if (result.status !== 0) {
  console.error(result.stderr || result.error?.message || 'supabase gen types failed')
  process.exit(result.status ?? 1)
}

const header = `// Generated by \`npm run db:types\` from Supabase project ${PROJECT_REF}.\n// Do not edit by hand: change supabase/schema.sql, apply it, then re-run.\n`
mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, header + result.stdout.replace(/\r\n/g, '\n'), 'utf8')
console.log(`Wrote ${OUT}`)
